import requests
import os
import openai

# Environment setup
SECURITY_ENDPOINT = "http://localhost:8000/security-gpt"  # Replace with your security analysis endpoint
OPTIMIZE_ENDPOINT = "http://localhost:8000/optimize-gpt"  # Replace with your optimization endpoint
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")  # Load OpenAI API key from environment

# Initialize OpenAI API key
openai.api_key = OPENAI_API_KEY

def get_modified_files():
    """
    Reads the list of modified files from 'modified_files.txt' generated by GitHub Actions.
    """
    try:
        with open("modified_files.txt", "r") as file:
            return [line.strip() for line in file.readlines()]
    except FileNotFoundError:
        raise Exception("No modified files found. Ensure 'modified_files.txt' exists and contains file paths.")

def read_file_contents(file_path):
    """
    Reads the contents of a file and returns it as a string.
    """
    try:
        with open(file_path, "r") as file:
            return file.read()
    except FileNotFoundError:
        raise Exception(f"File {file_path} not found.")

def check_security_vulnerabilities(code):
    """
    Calls the /security-gpt endpoint to check for security vulnerabilities.
    """
    try:
        print("Checking code for security vulnerabilities via /security-gpt...")
        response = requests.post(
            SECURITY_ENDPOINT,
            json={
                "prompt": code,
                "max_tokens": 300,
                "temperature": 0.7,
                "top_p": 1.0
            }
        )
        response.raise_for_status()
        return response.json()["response"]  # Ensure the correct response field is used
    except requests.exceptions.RequestException as e:
        raise Exception(f"Failed to call /security-gpt endpoint: {e}")

def get_optimized_code(code):
    """
    Calls the /optimize-gpt endpoint with the provided code snippet.
    """
    try:
        print("Optimizing code via /optimize-gpt...")
        response = requests.post(
            OPTIMIZE_ENDPOINT,
            json={
                "prompt": code,
                "max_tokens": 300,
                "temperature": 0.7,
                "top_p": 1.0
            }
        )
        response.raise_for_status()
        return response.json()["response"]
    except requests.exceptions.RequestException as e:
        raise Exception(f"Failed to call /optimize-gpt endpoint: {e}")

def validate_with_gpt(message):
    """
    Validates the message (security or optimization result) with GPT.
    """
    try:
        print("Validating the result with GPT...")
        messages = [
            {"role": "system", "content": "You are a code validation assistant. Your task is to validate the result."},
            {"role": "user", "content": f"Here is the result:\n\n{message}\n\nIs this OK or NOK? Respond with 'OK' or 'NOK' only."}
        ]
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=messages,
            max_tokens=10,
            temperature=0.0,
        )
        return response.choices[0].message["content"].strip()
    except openai.error.OpenAIError as e:
        raise Exception(f"Failed to validate result with GPT: {e}")

if __name__ == "__main__":
    try:
        # Step 1: Get the list of modified files
        modified_files = get_modified_files()

        for file in modified_files:
            print(f"Processing modified file: {file}")

            # Step 2: Read the file contents
            code_snippet = read_file_contents(file)

            # Step 3: Check for security vulnerabilities
            print(f"Running security analysis for {file}...")
            security_analysis = check_security_vulnerabilities(code_snippet)
            print(f"Security Analysis Result for {file}:\n{security_analysis}")

            # Validate security result
            security_validation = validate_with_gpt(security_analysis)
            print(f"Security Validation Result for {file}: {security_validation}")
            if security_validation != "OK":
                print(f"Security validation failed for {file}. Stopping the pipeline.")
                exit(1)  # Exit with non-zero status to fail the pipeline

            # Step 4: Optimize the code
            print(f"Running code optimization for {file}...")
            optimized_code = get_optimized_code(code_snippet)
            print(f"Optimized Code for {file}:\n{optimized_code}")

            # Validate optimized code
            optimization_validation = validate_with_gpt(optimized_code)
            print(f"Optimization Validation Result for {file}: {optimization_validation}")
            if optimization_validation != "OK":
                print(f"Optimization validation failed for {file}. Stopping the pipeline.")
                exit(1)  # Exit with non-zero status to fail the pipeline

        # If all files pass validation
        print("All modified files passed security and optimization validations. Proceeding with the pipeline.")

    except Exception as e:
        print(f"Pipeline execution failed: {e}")
        exit(1)
