name: Code Validation Pipeline

on:
  push:
    paths:
      - "Backend/sample_codes/**"
  pull_request:
    paths:
      - "Backend/sample_codes/**"

jobs:
  validate-code:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get modified files
        id: modified_files
        run: |
          git diff --name-only ${{ github.event.before || 'HEAD^' }} ${{ github.sha }} > modified_files.txt
          if (-not (Get-Content modified_files.txt)) {
            echo "No valid files to process."
            exit 0
          }
      - name: List Files in Backend
        run: ls -R Backend

      - name: Start Uvicorn Server
        shell: powershell
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          for ($i = 0; $i -lt 10; $i++) {
            try {
              Invoke-WebRequest -Uri http://localhost:8000/docs -UseBasicParsing
              echo "Server is up."
              break
            } catch {
              echo "Waiting for server..."
              Start-Sleep -Seconds 2
            }
          }
        working-directory: Backend

      - name: Debug modified files
        run: |
          echo "Modified files:"
          cat modified_files.txt

      - name: Run validation script
        run: python Backend/app/ci_cd/run_gpt_pipeline.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
