name: Code Validation Pipeline

on:
  pull_request:
    paths:
      - "Backend/sample_codes/**"

jobs:
  validate-code:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get modified files
        id: modified_files
        shell: powershell
        run: |
          git diff --name-only ${{ github.event.before || 'HEAD^' }} ${{ github.sha }} > modified_files.txt
          if (-not (Test-Path modified_files.txt) -or -not (Get-Content modified_files.txt)) {
            echo "No valid files to process."
            exit 0
          }

      - name: List Files in Backend
        run: ls -R Backend
      
      - name: Start Uvicorn Server
        shell: powershell
        run: |
          Start-Process -FilePath uvicorn -ArgumentList "app.main:app", "--host", "0.0.0.0", "--port", "8000" -NoNewWindow -PassThru
        working-directory: Backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Wait for Server
        run: |
          echo "Waiting for FastAPI server to start..."
          sleep 10  # Wait for the server to initialize

      - name: Debug modified files
        run: |
          echo "Modified files:"
          cat modified_files.txt

      - name: Run validation script
        run: python Backend/app/ci_cd/run_gpt_pipeline.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
