name: Code Validation Pipeline

on:
  push:
    paths:
      - "Backend/sample_codes/**"  # Trigger only if files in Backend/sample_codes are modified
  pull_request:
    paths:
      - "Backend/sample_codes/**"  # Trigger only if files in Backend/sample_codes are modified

jobs:
  validate-code:
    runs-on: [self-hosted, Windows, X64]  # Ensure the job runs on your self-hosted Windows runner

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Verify Python version (For Debugging)
      - name: Verify Python version
        run: python --version

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify Python version clearly (e.g., 3.10 instead of "3.10.x")
          cache: "pip"  # Caches dependencies installed via pip to save time in subsequent runs

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      # Step 5: Get modified files
      - name: Get modified files
        id: modified_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt
          echo "Modified files:"
          cat modified_files.txt

      # Step 6: Debug environment variables (Optional for Debugging)
      - name: Debug environment
        run: env

      # Step 7: Run the validation script
      - name: Run validation script
        run: python app/ci_cd/run_gpt_pipeline.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
