name: Code Validation Pipeline

on:
  push:
    paths:
      - "Backend/sample_codes/**"  # Trigger only if files in Backend/sample_codes are modified
  pull_request:
    paths:
      - "Backend/sample_codes/**"  # Trigger only if files in Backend/sample_codes are modified

jobs:
  validate-code:
    runs-on: self-hosted  # Ensure your runner is set up correctly

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Backend/requirements.txt

      # Step 4: Get modified files
      - name: Get modified files
        id: modified_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt

      # Step 5: Run the validation script
      - name: Run validation script
        run: python app/ci_cd/run_gpt_pipeline.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
